# Generated by Django 4.2.3 on 2023-07-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0004_book_genre_alter_collection_featured_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='featured_book',
        ),
    ]
