# Generated by Django 4.2.3 on 2023-07-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0008_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
