# Generated by Django 4.2.3 on 2023-07-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0011_order_customer_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='BookStore.order'),
        ),
        migrations.CreateModel(
            name='BookFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='BookStore/file')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStore.book')),
            ],
        ),
    ]
